# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: 'windows-latest'

strategy:
  matrix:
    Python310:
      python.version: '3.10'

steps:
- powershell: |
    $ProgressPreference = 'SilentlyContinue'
    Invoke-WebRequest -Uri "https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/..." -OutFile "MicrosoftEdgeSetup.exe"
    Start-Process -FilePath "MicrosoftEdgeSetup.exe" -ArgumentList "/silent /install" -Wait
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $edgeVersion = (Get-Item (Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\msedge.exe').'(Default)').VersionInfo.FileVersion
      Invoke-WebRequest "https://msedgedriver.azureedge.net/$edgeVersion/edgedriver_win64.zip" -OutFile edgedriver.zip
      Expand-Archive edgedriver.zip -DestinationPath $env:AGENT_TEMPDIRECTORY
      Write-Host "##vso[task.prependpath]$env:AGENT_TEMPDIRECTORY"

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pip install pytest pytest-azurepipelines
    pytest
  displayName: 'pytest'
